### ISSUE TITLE
Max age and setMaxInactiveInterval in cookie config missing

### ISSUE THREAD

**Issue by botic** [grob/httpserver#7]
There is no way to set the max age of a session cookie with `setMaxAge(int maxAge)`. I think this is related with `setMaxInactiveInterval()`, but not the same. One sets the cookie lifetime, the other the refresh time / invalidation timeout for a session itself. Both options cannot be configured with the current httpserver afais.

**Comment by grob** [comment]
`sessionsMaxInactiveInterval` and `cookieMaxAge` can now be passed as options to  `serveApplication()`. thanks for spotting this!
